export const Dailyplans = [
  // {
  //   title: "Arena Only",
  //   description: "Perfect for individuals who just what to use the arena",
  //   price: "Custom Price",
  //   priceLabel: "/month",
  //   features: [
  //     "Account Registration & Login",
  //     "Browse Gyms & Services",
  //     "AI trainer recommendations",
  //     "Free outdoor events registration",
  //     "Arena (Outdoor Callisthenics) Access",
  //     "Event Participation (Public / Corporate)",
  //     "Merchandise store access",
  //     "Basic workout videos",
  //     "AI Workout Videos",
  //   ],
  //   buttonText: "Not Available",
  //   onAction: () => {
  //     console.log("Regular plan selected");
  //   },
  // },
  {
    title: "Regular",
    description: "Perfect for individuals getting started",
    price: "Free",
    priceLabel: "/day",
    features: [
      "Account Registration & Login",
      "Browse Gyms & Services",
      "AI trainer recommendations",
      "Free outdoor events registration",
      "Arena (Outdoor Callisthenics) Access",
      "Event Participation (Public / Corporate)",
      "Merchandise store access",
      "Basic workout videos",
      "AI Workout Videos",
    ],
    buttonText: "Choose Regular",
    onAction: () => {
      console.log("Regular plan selected");
    },
  },

  {
    title: "Standard",
    description: "Best value for professionals",
    price: "₦3,499 ",
    priceSlash: "₦2,999",
    priceLabel: "/daily",
    highlight: true,
    features: [
      "Unlimited projects",
      "Access to Indoor Gym",
      "Priority support",
      "Multi-Location Access",
      "Advanced analytics",
      "Account Registration & Login",
      "Browse Gyms & Services",
      "AI trainer recommendations",
      "Free outdoor events registration",
      "Arena (Outdoor Callisthenics) Access",
      "Event Participation (Public / Corporate)",
      "Merchandise store access",
      "Basic workout videos",
      "AI Workout Videos",
    ],
    buttonText: "Choose Standard",
    onAction: () => {
      console.log("Standard plan selected");
    },
  },

  {
    title: "Premium",
    description: "Best value for professionals",
    price: "₦4,599 ",
    priceSlash: "₦5,499",
    priceLabel: "/daily",
    // highlight: true,
    features: [
      "Unlimited projects",
      "Trainer-Led Sessions",
      "Coaching & Personalised Programs",
      "Priority support",
      "Advanced analytics",
      "Affiliate Gym Access",
      "Account Registration & Login",
      "Browse Gyms & Services",
      "AI trainer recommendations",
      "Free outdoor events registration",
      "Arena (Outdoor Callisthenics) Access",
      "Event Participation (Public / Corporate)",
      "Merchandise store access",
      "Basic workout videos",
      "AI Workout Videos",
    ],
    buttonText: "Choose Premium",
    onAction: () => {
      console.log("Standard plan selected");
    },
  },
  // {
  //   title: "Corporate",
  //   description: "Designed for large teams & businesses",
  //   price: "₦25,000",
  //   priceLabel: "/month",
  //   features: [
  //     "Team collaboration",
  //     "Dedicated account manager",
  //     "Custom integrations",
  //   ],
  //   buttonText: "Contact Sales",
  //   onAction: () => {
  //     console.log("Corporate plan selected");
  //   },
  // },
];

export const MonthlyPlans = [
  {
    title: "Free",
    description: "",
    price: "Custom Pricing /",
    // priceSlash: "₦2,999",
    priceLabel: "Monthly",
    buttonText: "Contact Sales",
    features: [
      "Account Registration & Login",
      "Bulk staff onboarding",
      "Corporate admin dashboard",
      "Usage analytics & reporting",
      "Flexible staff role assignments",
      "Corporate billing management",
      "Team wellness challenges",
      "Dedicated account manager",
    ],
  },
  {
    title: "Standard",
    description: "Group classes and gym access at your designated location",
    price: "₦84,999 /",
    priceSlash: "₦104,999",
    priceLabel: "Monthly",
    buttonText: "Renew",
    features: [
      "All free plan features",
      "Access to Indoor Gym",
      "Access to designated gym location",
      "Unlimited group class bookings",
      "Equipment usage & lockers",
      "Fitness progress tracking",
      "Account Registration & Login",
      "Bulk staff onboarding",
      "Corporate admin dashboard",
      "Usage analytics & reporting",
      "Flexible staff role assignments",
      "Corporate billing management",
      "Team wellness challenges",
      "Dedicated account manager",
    ],
  },
  {
    title: "Premium",
    description: "Personal training and nationwide access to all facilities",
    price: "₦30,999 /",
    priceSlash: "₦50,499",
    priceLabel: "Monthly",
    buttonText: "Upgrade",
    highlight: true,
    features: [
      "All standard plan features",
      "Browse Gyms & Services",
      "Custom workout & diet plans",
      "Access to ALL Eugym locations",
      "Affiliate hotel gym access",
      "Premium indoor activities",
      "Priority class bookings",
      "Account Registration & Login",
      "Bulk staff onboarding",
      "Corporate admin dashboard",
      "Usage analytics & reporting",
      "Flexible staff role assignments",
      "Corporate billing management",
      "Team wellness challenges",
      "Dedicated account manager",
    ],
  },
  // {
  //   title: "Corporate",
  //   description: "Bulk wellness packages for organizations and companies",
  //   price: "Custom Pricing",
  //   priceSlash: "₦104,999",
  //   priceLabel: "Monthly",
  //   buttonText: "Contact Sales",
  //   features: [
  //     "Bulk staff onboarding",
  //     "Corporate admin dashboard",
  //     "Usage analytics & reporting",
  //     "Flexible staff role assignments",
  //     "Corporate billing management",
  //     "Team wellness challenges",
  //     "Dedicated account manager",
  //   ],
  // },
];

export const QuarterlyPlans = [
  {
    title: "Free",
    description: "",
    price: "Custom Pricing /",
    priceSlash: "₦2,999",
    priceLabel: "Quarterly",
    buttonText: "Contact Sales",
    features: [
      "Account Registration & Login",
      "Browse Gyms & Services",
      "Bulk staff onboarding",
      "Corporate admin dashboard",
      "Usage analytics & reporting",
      "Flexible staff role assignments",
      "Corporate billing management",
      "Team wellness challenges",
      "Dedicated account manager",
    ],
  },
  {
    title: "Standard",
    description: "Group classes and gym access at your designated location",
    price: "₦84,999 /",
    priceSlash: "₦104,999",
    priceLabel: "Quarterly",
    buttonText: "Renew",
    features: [
      "Account Registration & Login",
      "Browse Gyms & Services",
      "All free plan features",
      "Access to designated gym location",
      "Arena (Outdoor Callisthenics) Access",
      "Check-in / Attendance Tracking",
      "Unlimited group class bookings",
      "Equipment usage & lockers",
      "Fitness progress tracking",
      "Bulk staff onboarding",
      "Corporate admin dashboard",
      "Usage analytics & reporting",
      "Flexible staff role assignments",
      "Corporate billing management",
      "Team wellness challenges",
      "Dedicated account manager",
    ],
  },
  {
    title: "Premium",
    description: "Personal training and nationwide access to all facilities",
    price: "₦119,999/",
    priceSlash: "₦149,999",
    priceLabel: "Quarterly",
    buttonText: "Upgrade",
    highlight: true,
    features: [
      "All standard plan features",
      "Custom workout & diet plans",
      "Access to ALL Eugym locations",
      "Check-in / Attendance Tracking",
      "Affiliate hotel gym access",
      "Premium indoor activities",
      "Priority class bookings",
      "Account Registration & Login",
      "Browse Gyms & Services",
      "Bulk staff onboarding",
      "Corporate admin dashboard",
      "Usage analytics & reporting",
      "Flexible staff role assignments",
      "Corporate billing management",
      "Team wellness challenges",
      "Dedicated account manager",
    ],
  },
  // {
  //   title: "Corporate",
  //   description: "Bulk wellness packages for organizations and companies",
  //   price: "Custom Pricing",
  //   priceLabel: "Quarterly",
  //   buttonText: "Contact Sales",
  //   features: [
  //     "Bulk staff onboarding",
  //     "Corporate admin dashboard",
  //     "Usage analytics & reporting",
  //     "Flexible staff role assignments",
  //     "Corporate billing management",
  //     "Team wellness challenges",
  //     "Dedicated account manager",
  //   ],
  // },
];
